### ISSUE TITLE
Ability to pass other variables to container [request]

### ISSUE THREAD

**Issue by raindropworks** [theBlackDragon/conan-exiles-dedicated-server#2]
Is there a way to add other features to pass through to the server, such as server passwords and such? I've been using the dedicated launcher the devs made, and it actually works surprisingly well for me, but I have a dedicated gaming server I want to move it too instead of my desktop, so I wouldn't be able to use their DSL

**Comment by theBlackDragon** [comment]
Hmm, I usually just edit the server configurations directly. If they are supported as parameters by the binary I can definitely look into exposing those as options though.

**Comment by theBlackDragon** [comment]
I've added a CONAN_ARGS environment variable that is passed on to the server process.

You'd have to manually add the parameters that were passed up to this point if you want to retain them when adding additional parameters. Please let me know if things work as expected.

**Comment by theBlackDragon** [comment]
Requested functionality was added, can re-open should there be issues with it.
