### ISSUE TITLE
Getting permission denied error on pulling the image

### ISSUE THREAD

**Issue by DutchKevv** [theBlackDragon/conan-exiles-dedicated-server#4]
Error response from daemon: pull access denied for bgeens/conan-exiles-server, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by theBlackDragon** [comment]
You need to build the image, per the instructions, it's not uploaded to Dockerhub at this time.

**Comment by heusmich** [comment]
Hi,

I get the same error like DutchKevv.
But to be honest I don´t know exactly how I can build the image.

I created a folder /home/conanexiles/ and in this folder I created a file "docker-compose.yml".
When I execute the command "docker-compose up", I get the same error as above.
Would you please give me a step by step guide how to create the image and get the server up and running?
I´m still a beginner in Docker and would be glad if you could help me in this case.

Edit: And by the way sorry that I reply to this old post, but I didn´t want to open a new one when I have the same problem. But if you want I can open a new one... ;)

Thx
